// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: product/tag.dev.proto

package tagpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	productpb "proto/v1/productpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *productpb.Tag         `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	ProductCount  int32                  `protobuf:"varint,2,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagStats) Reset() {
	*x = TagStats{}
	mi := &file_product_tag_dev_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagStats) ProtoMessage() {}

func (x *TagStats) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagStats.ProtoReflect.Descriptor instead.
func (*TagStats) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{0}
}

func (x *TagStats) GetTag() *productpb.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *TagStats) GetProductCount() int32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

type TagDetail struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Tag           *productpb.Tag              `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Products      []*productpb.ProductSummary `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	TotalProducts int32                       `protobuf:"varint,3,opt,name=total_products,json=totalProducts,proto3" json:"total_products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagDetail) Reset() {
	*x = TagDetail{}
	mi := &file_product_tag_dev_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDetail) ProtoMessage() {}

func (x *TagDetail) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDetail.ProtoReflect.Descriptor instead.
func (*TagDetail) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{1}
}

func (x *TagDetail) GetTag() *productpb.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *TagDetail) GetProducts() []*productpb.ProductSummary {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *TagDetail) GetTotalProducts() int32 {
	if x != nil {
		return x.TotalProducts
	}
	return 0
}

type TagCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          *string                `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagCreateRequest) Reset() {
	*x = TagCreateRequest{}
	mi := &file_product_tag_dev_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagCreateRequest) ProtoMessage() {}

func (x *TagCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagCreateRequest.ProtoReflect.Descriptor instead.
func (*TagCreateRequest) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{2}
}

func (x *TagCreateRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *TagCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagCreateRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

type TagGetRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId              string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	IncludeProductCount bool                   `protobuf:"varint,3,opt,name=include_product_count,json=includeProductCount,proto3" json:"include_product_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TagGetRequest) Reset() {
	*x = TagGetRequest{}
	mi := &file_product_tag_dev_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagGetRequest) ProtoMessage() {}

func (x *TagGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagGetRequest.ProtoReflect.Descriptor instead.
func (*TagGetRequest) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{3}
}

func (x *TagGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagGetRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *TagGetRequest) GetIncludeProductCount() bool {
	if x != nil {
		return x.IncludeProductCount
	}
	return false
}

type TagGetDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagGetDetailRequest) Reset() {
	*x = TagGetDetailRequest{}
	mi := &file_product_tag_dev_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagGetDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagGetDetailRequest) ProtoMessage() {}

func (x *TagGetDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagGetDetailRequest.ProtoReflect.Descriptor instead.
func (*TagGetDetailRequest) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{4}
}

func (x *TagGetDetailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagGetDetailRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *TagGetDetailRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TagGetDetailRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TagListRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ShopId              string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Search              *string                `protobuf:"bytes,2,opt,name=search,proto3,oneof" json:"search,omitempty"`
	IncludeProductCount bool                   `protobuf:"varint,3,opt,name=include_product_count,json=includeProductCount,proto3" json:"include_product_count,omitempty"`
	Page                int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize            int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TagListRequest) Reset() {
	*x = TagListRequest{}
	mi := &file_product_tag_dev_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListRequest) ProtoMessage() {}

func (x *TagListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListRequest.ProtoReflect.Descriptor instead.
func (*TagListRequest) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{5}
}

func (x *TagListRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *TagListRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *TagListRequest) GetIncludeProductCount() bool {
	if x != nil {
		return x.IncludeProductCount
	}
	return false
}

func (x *TagListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TagListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TagUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Slug          *string                `protobuf:"bytes,4,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagUpdateRequest) Reset() {
	*x = TagUpdateRequest{}
	mi := &file_product_tag_dev_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagUpdateRequest) ProtoMessage() {}

func (x *TagUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagUpdateRequest.ProtoReflect.Descriptor instead.
func (*TagUpdateRequest) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{6}
}

func (x *TagUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagUpdateRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *TagUpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TagUpdateRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

type TagDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagDeleteRequest) Reset() {
	*x = TagDeleteRequest{}
	mi := &file_product_tag_dev_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDeleteRequest) ProtoMessage() {}

func (x *TagDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDeleteRequest.ProtoReflect.Descriptor instead.
func (*TagDeleteRequest) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{7}
}

func (x *TagDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagDeleteRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type TagAssignRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductId       string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId          string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	TagIds          []string               `protobuf:"bytes,3,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	ReplaceExisting bool                   `protobuf:"varint,4,opt,name=replace_existing,json=replaceExisting,proto3" json:"replace_existing,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TagAssignRequest) Reset() {
	*x = TagAssignRequest{}
	mi := &file_product_tag_dev_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagAssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagAssignRequest) ProtoMessage() {}

func (x *TagAssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagAssignRequest.ProtoReflect.Descriptor instead.
func (*TagAssignRequest) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{8}
}

func (x *TagAssignRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TagAssignRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *TagAssignRequest) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *TagAssignRequest) GetReplaceExisting() bool {
	if x != nil {
		return x.ReplaceExisting
	}
	return false
}

type TagRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	TagIds        []string               `protobuf:"bytes,3,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagRemoveRequest) Reset() {
	*x = TagRemoveRequest{}
	mi := &file_product_tag_dev_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagRemoveRequest) ProtoMessage() {}

func (x *TagRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagRemoveRequest.ProtoReflect.Descriptor instead.
func (*TagRemoveRequest) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{9}
}

func (x *TagRemoveRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TagRemoveRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *TagRemoveRequest) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type TagGetByProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagGetByProductRequest) Reset() {
	*x = TagGetByProductRequest{}
	mi := &file_product_tag_dev_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagGetByProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagGetByProductRequest) ProtoMessage() {}

func (x *TagGetByProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagGetByProductRequest.ProtoReflect.Descriptor instead.
func (*TagGetByProductRequest) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{10}
}

func (x *TagGetByProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TagGetByProductRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type TagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *TagStats              `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResponse) Reset() {
	*x = TagResponse{}
	mi := &file_product_tag_dev_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResponse) ProtoMessage() {}

func (x *TagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResponse.ProtoReflect.Descriptor instead.
func (*TagResponse) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{11}
}

func (x *TagResponse) GetTag() *TagStats {
	if x != nil {
		return x.Tag
	}
	return nil
}

type TagDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagDetail     *TagDetail             `protobuf:"bytes,1,opt,name=tag_detail,json=tagDetail,proto3" json:"tag_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagDetailResponse) Reset() {
	*x = TagDetailResponse{}
	mi := &file_product_tag_dev_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDetailResponse) ProtoMessage() {}

func (x *TagDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDetailResponse.ProtoReflect.Descriptor instead.
func (*TagDetailResponse) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{12}
}

func (x *TagDetailResponse) GetTagDetail() *TagDetail {
	if x != nil {
		return x.TagDetail
	}
	return nil
}

type TagListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagStats            `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListResponse) Reset() {
	*x = TagListResponse{}
	mi := &file_product_tag_dev_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListResponse) ProtoMessage() {}

func (x *TagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListResponse.ProtoReflect.Descriptor instead.
func (*TagListResponse) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{13}
}

func (x *TagListResponse) GetTags() []*TagStats {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TagListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TagListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TagListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TagAssignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignedTags  []*productpb.Tag       `protobuf:"bytes,1,rep,name=assigned_tags,json=assignedTags,proto3" json:"assigned_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagAssignResponse) Reset() {
	*x = TagAssignResponse{}
	mi := &file_product_tag_dev_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagAssignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagAssignResponse) ProtoMessage() {}

func (x *TagAssignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagAssignResponse.ProtoReflect.Descriptor instead.
func (*TagAssignResponse) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{14}
}

func (x *TagAssignResponse) GetAssignedTags() []*productpb.Tag {
	if x != nil {
		return x.AssignedTags
	}
	return nil
}

type TagGetByProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*productpb.Tag       `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagGetByProductResponse) Reset() {
	*x = TagGetByProductResponse{}
	mi := &file_product_tag_dev_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagGetByProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagGetByProductResponse) ProtoMessage() {}

func (x *TagGetByProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_tag_dev_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagGetByProductResponse.ProtoReflect.Descriptor instead.
func (*TagGetByProductResponse) Descriptor() ([]byte, []int) {
	return file_product_tag_dev_proto_rawDescGZIP(), []int{15}
}

func (x *TagGetByProductResponse) GetTags() []*productpb.Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_product_tag_dev_proto protoreflect.FileDescriptor

const file_product_tag_dev_proto_rawDesc = "" +
	"\n" +
	"\x15product/tag.dev.proto\x12\aproduct\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19product/product.dev.proto\"O\n" +
	"\bTagStats\x12\x1e\n" +
	"\x03tag\x18\x01 \x01(\v2\f.product.TagR\x03tag\x12#\n" +
	"\rproduct_count\x18\x02 \x01(\x05R\fproductCount\"\x87\x01\n" +
	"\tTagDetail\x12\x1e\n" +
	"\x03tag\x18\x01 \x01(\v2\f.product.TagR\x03tag\x123\n" +
	"\bproducts\x18\x02 \x03(\v2\x17.product.ProductSummaryR\bproducts\x12%\n" +
	"\x0etotal_products\x18\x03 \x01(\x05R\rtotalProducts\"a\n" +
	"\x10TagCreateRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x00R\x04slug\x88\x01\x01B\a\n" +
	"\x05_slug\"l\n" +
	"\rTagGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x122\n" +
	"\x15include_product_count\x18\x03 \x01(\bR\x13includeProductCount\"o\n" +
	"\x13TagGetDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb6\x01\n" +
	"\x0eTagListRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x1b\n" +
	"\x06search\x18\x02 \x01(\tH\x00R\x06search\x88\x01\x01\x122\n" +
	"\x15include_product_count\x18\x03 \x01(\bR\x13includeProductCount\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSizeB\t\n" +
	"\a_search\"\x7f\n" +
	"\x10TagUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x04 \x01(\tH\x01R\x04slug\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slug\";\n" +
	"\x10TagDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\"\x8e\x01\n" +
	"\x10TagAssignRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x17\n" +
	"\atag_ids\x18\x03 \x03(\tR\x06tagIds\x12)\n" +
	"\x10replace_existing\x18\x04 \x01(\bR\x0freplaceExisting\"c\n" +
	"\x10TagRemoveRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x17\n" +
	"\atag_ids\x18\x03 \x03(\tR\x06tagIds\"P\n" +
	"\x16TagGetByProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\"2\n" +
	"\vTagResponse\x12#\n" +
	"\x03tag\x18\x01 \x01(\v2\x11.product.TagStatsR\x03tag\"F\n" +
	"\x11TagDetailResponse\x121\n" +
	"\n" +
	"tag_detail\x18\x01 \x01(\v2\x12.product.TagDetailR\ttagDetail\"\x7f\n" +
	"\x0fTagListResponse\x12%\n" +
	"\x04tags\x18\x01 \x03(\v2\x11.product.TagStatsR\x04tags\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"F\n" +
	"\x11TagAssignResponse\x121\n" +
	"\rassigned_tags\x18\x01 \x03(\v2\f.product.TagR\fassignedTags\";\n" +
	"\x17TagGetByProductResponse\x12 \n" +
	"\x04tags\x18\x01 \x03(\v2\f.product.TagR\x04tags2\xdb\x04\n" +
	"\n" +
	"TagService\x129\n" +
	"\x06Create\x12\x19.product.TagCreateRequest\x1a\x14.product.TagResponse\x123\n" +
	"\x03Get\x12\x16.product.TagGetRequest\x1a\x14.product.TagResponse\x12E\n" +
	"\tGetDetail\x12\x1c.product.TagGetDetailRequest\x1a\x1a.product.TagDetailResponse\x129\n" +
	"\x04List\x12\x17.product.TagListRequest\x1a\x18.product.TagListResponse\x129\n" +
	"\x06Update\x12\x19.product.TagUpdateRequest\x1a\x14.product.TagResponse\x12;\n" +
	"\x06Delete\x12\x19.product.TagDeleteRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x0fAssignToProduct\x12\x19.product.TagAssignRequest\x1a\x1a.product.TagAssignResponse\x12F\n" +
	"\x11RemoveFromProduct\x12\x19.product.TagRemoveRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\fGetByProduct\x12\x1f.product.TagGetByProductRequest\x1a .product.TagGetByProductResponseB\x16Z\x14proto/v1/tagpb;tagpbb\x06proto3"

var (
	file_product_tag_dev_proto_rawDescOnce sync.Once
	file_product_tag_dev_proto_rawDescData []byte
)

func file_product_tag_dev_proto_rawDescGZIP() []byte {
	file_product_tag_dev_proto_rawDescOnce.Do(func() {
		file_product_tag_dev_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_tag_dev_proto_rawDesc), len(file_product_tag_dev_proto_rawDesc)))
	})
	return file_product_tag_dev_proto_rawDescData
}

var file_product_tag_dev_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_product_tag_dev_proto_goTypes = []any{
	(*TagStats)(nil),                 // 0: product.TagStats
	(*TagDetail)(nil),                // 1: product.TagDetail
	(*TagCreateRequest)(nil),         // 2: product.TagCreateRequest
	(*TagGetRequest)(nil),            // 3: product.TagGetRequest
	(*TagGetDetailRequest)(nil),      // 4: product.TagGetDetailRequest
	(*TagListRequest)(nil),           // 5: product.TagListRequest
	(*TagUpdateRequest)(nil),         // 6: product.TagUpdateRequest
	(*TagDeleteRequest)(nil),         // 7: product.TagDeleteRequest
	(*TagAssignRequest)(nil),         // 8: product.TagAssignRequest
	(*TagRemoveRequest)(nil),         // 9: product.TagRemoveRequest
	(*TagGetByProductRequest)(nil),   // 10: product.TagGetByProductRequest
	(*TagResponse)(nil),              // 11: product.TagResponse
	(*TagDetailResponse)(nil),        // 12: product.TagDetailResponse
	(*TagListResponse)(nil),          // 13: product.TagListResponse
	(*TagAssignResponse)(nil),        // 14: product.TagAssignResponse
	(*TagGetByProductResponse)(nil),  // 15: product.TagGetByProductResponse
	(*productpb.Tag)(nil),            // 16: product.Tag
	(*productpb.ProductSummary)(nil), // 17: product.ProductSummary
	(*emptypb.Empty)(nil),            // 18: google.protobuf.Empty
}
var file_product_tag_dev_proto_depIdxs = []int32{
	16, // 0: product.TagStats.tag:type_name -> product.Tag
	16, // 1: product.TagDetail.tag:type_name -> product.Tag
	17, // 2: product.TagDetail.products:type_name -> product.ProductSummary
	0,  // 3: product.TagResponse.tag:type_name -> product.TagStats
	1,  // 4: product.TagDetailResponse.tag_detail:type_name -> product.TagDetail
	0,  // 5: product.TagListResponse.tags:type_name -> product.TagStats
	16, // 6: product.TagAssignResponse.assigned_tags:type_name -> product.Tag
	16, // 7: product.TagGetByProductResponse.tags:type_name -> product.Tag
	2,  // 8: product.TagService.Create:input_type -> product.TagCreateRequest
	3,  // 9: product.TagService.Get:input_type -> product.TagGetRequest
	4,  // 10: product.TagService.GetDetail:input_type -> product.TagGetDetailRequest
	5,  // 11: product.TagService.List:input_type -> product.TagListRequest
	6,  // 12: product.TagService.Update:input_type -> product.TagUpdateRequest
	7,  // 13: product.TagService.Delete:input_type -> product.TagDeleteRequest
	8,  // 14: product.TagService.AssignToProduct:input_type -> product.TagAssignRequest
	9,  // 15: product.TagService.RemoveFromProduct:input_type -> product.TagRemoveRequest
	10, // 16: product.TagService.GetByProduct:input_type -> product.TagGetByProductRequest
	11, // 17: product.TagService.Create:output_type -> product.TagResponse
	11, // 18: product.TagService.Get:output_type -> product.TagResponse
	12, // 19: product.TagService.GetDetail:output_type -> product.TagDetailResponse
	13, // 20: product.TagService.List:output_type -> product.TagListResponse
	11, // 21: product.TagService.Update:output_type -> product.TagResponse
	18, // 22: product.TagService.Delete:output_type -> google.protobuf.Empty
	14, // 23: product.TagService.AssignToProduct:output_type -> product.TagAssignResponse
	18, // 24: product.TagService.RemoveFromProduct:output_type -> google.protobuf.Empty
	15, // 25: product.TagService.GetByProduct:output_type -> product.TagGetByProductResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_product_tag_dev_proto_init() }
func file_product_tag_dev_proto_init() {
	if File_product_tag_dev_proto != nil {
		return
	}
	file_product_tag_dev_proto_msgTypes[2].OneofWrappers = []any{}
	file_product_tag_dev_proto_msgTypes[5].OneofWrappers = []any{}
	file_product_tag_dev_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_tag_dev_proto_rawDesc), len(file_product_tag_dev_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_tag_dev_proto_goTypes,
		DependencyIndexes: file_product_tag_dev_proto_depIdxs,
		MessageInfos:      file_product_tag_dev_proto_msgTypes,
	}.Build()
	File_product_tag_dev_proto = out.File
	file_product_tag_dev_proto_goTypes = nil
	file_product_tag_dev_proto_depIdxs = nil
}
