// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: product/product.dev.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId         string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CategoryId     *string                `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Sku            *string                `protobuf:"bytes,4,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	Barcode        *string                `protobuf:"bytes,5,opt,name=barcode,proto3,oneof" json:"barcode,omitempty"`
	Name           string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Detail         *string                `protobuf:"bytes,8,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	Price          float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	CostPrice      float64                `protobuf:"fixed64,10,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	CompareAtPrice *float64               `protobuf:"fixed64,11,opt,name=compare_at_price,json=compareAtPrice,proto3,oneof" json:"compare_at_price,omitempty"`
	StockQuantity  int32                  `protobuf:"varint,12,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	MinStockLevel  int32                  `protobuf:"varint,13,opt,name=min_stock_level,json=minStockLevel,proto3" json:"min_stock_level,omitempty"`
	MaxStockLevel  *int32                 `protobuf:"varint,14,opt,name=max_stock_level,json=maxStockLevel,proto3,oneof" json:"max_stock_level,omitempty"`
	Unit           string                 `protobuf:"bytes,15,opt,name=unit,proto3" json:"unit,omitempty"`
	Weight         *float64               `protobuf:"fixed64,16,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	WeightUnit     string                 `protobuf:"bytes,17,opt,name=weight_unit,json=weightUnit,proto3" json:"weight_unit,omitempty"`
	ThumbnailIndex int32                  `protobuf:"varint,18,opt,name=thumbnail_index,json=thumbnailIndex,proto3" json:"thumbnail_index,omitempty"`
	IsActive       bool                   `protobuf:"varint,19,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsTaxable      bool                   `protobuf:"varint,20,opt,name=is_taxable,json=isTaxable,proto3" json:"is_taxable,omitempty"`
	TaxRate        float64                `protobuf:"fixed64,21,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	TrackInventory bool                   `protobuf:"varint,22,opt,name=track_inventory,json=trackInventory,proto3" json:"track_inventory,omitempty"`
	AllowBackorder bool                   `protobuf:"varint,23,opt,name=allow_backorder,json=allowBackorder,proto3" json:"allow_backorder,omitempty"`
	IsFeatured     bool                   `protobuf:"varint,24,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	SortOrder      int32                  `protobuf:"varint,25,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,26,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,28,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,29,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_product_dev_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *Product) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *Product) GetBarcode() string {
	if x != nil && x.Barcode != nil {
		return *x.Barcode
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Product) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCostPrice() float64 {
	if x != nil {
		return x.CostPrice
	}
	return 0
}

func (x *Product) GetCompareAtPrice() float64 {
	if x != nil && x.CompareAtPrice != nil {
		return *x.CompareAtPrice
	}
	return 0
}

func (x *Product) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Product) GetMinStockLevel() int32 {
	if x != nil {
		return x.MinStockLevel
	}
	return 0
}

func (x *Product) GetMaxStockLevel() int32 {
	if x != nil && x.MaxStockLevel != nil {
		return *x.MaxStockLevel
	}
	return 0
}

func (x *Product) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Product) GetWeight() float64 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *Product) GetWeightUnit() string {
	if x != nil {
		return x.WeightUnit
	}
	return ""
}

func (x *Product) GetThumbnailIndex() int32 {
	if x != nil {
		return x.ThumbnailIndex
	}
	return 0
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetIsTaxable() bool {
	if x != nil {
		return x.IsTaxable
	}
	return false
}

func (x *Product) GetTaxRate() float64 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *Product) GetTrackInventory() bool {
	if x != nil {
		return x.TrackInventory
	}
	return false
}

func (x *Product) GetAllowBackorder() bool {
	if x != nil {
		return x.AllowBackorder
	}
	return false
}

func (x *Product) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *Product) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Product) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ProductSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sku           *string                `protobuf:"bytes,3,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSummary) Reset() {
	*x = ProductSummary{}
	mi := &file_product_product_dev_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSummary) ProtoMessage() {}

func (x *ProductSummary) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSummary.ProtoReflect.Descriptor instead.
func (*ProductSummary) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{1}
}

func (x *ProductSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSummary) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *ProductSummary) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductSummary) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ProductDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Category      *CategoryInfo          `protobuf:"bytes,2,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Media         []*Media               `protobuf:"bytes,3,rep,name=media,proto3" json:"media,omitempty"`
	Variants      []*Variant             `protobuf:"bytes,4,rep,name=variants,proto3" json:"variants,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Shop          *ShopInfo              `protobuf:"bytes,6,opt,name=shop,proto3,oneof" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDetail) Reset() {
	*x = ProductDetail{}
	mi := &file_product_product_dev_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetail) ProtoMessage() {}

func (x *ProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetail.ProtoReflect.Descriptor instead.
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{2}
}

func (x *ProductDetail) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ProductDetail) GetCategory() *CategoryInfo {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *ProductDetail) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *ProductDetail) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *ProductDetail) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProductDetail) GetShop() *ShopInfo {
	if x != nil {
		return x.Shop
	}
	return nil
}

type CategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	ParentId      *string                `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Parent        *CategoryInfo          `protobuf:"bytes,5,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_product_product_dev_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryInfo) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *CategoryInfo) GetParent() *CategoryInfo {
	if x != nil {
		return x.Parent
	}
	return nil
}

type ShopInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl       *string                `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopInfo) Reset() {
	*x = ShopInfo{}
	mi := &file_product_product_dev_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfo) ProtoMessage() {}

func (x *ShopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfo.ProtoReflect.Descriptor instead.
func (*ShopInfo) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{4}
}

func (x *ShopInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShopInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopInfo) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,3,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"` // "image" or "video"
	DisplayOrder  int32                  `protobuf:"varint,5,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	IsThumbnail   bool                   `protobuf:"varint,6,opt,name=is_thumbnail,json=isThumbnail,proto3" json:"is_thumbnail,omitempty"`
	AltText       *string                `protobuf:"bytes,7,opt,name=alt_text,json=altText,proto3,oneof" json:"alt_text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_product_product_dev_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{5}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Media) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Media) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Media) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *Media) GetIsThumbnail() bool {
	if x != nil {
		return x.IsThumbnail
	}
	return false
}

func (x *Media) GetAltText() string {
	if x != nil && x.AltText != nil {
		return *x.AltText
	}
	return ""
}

func (x *Media) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Variant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId      string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku            *string                `protobuf:"bytes,3,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	Barcode        *string                `protobuf:"bytes,4,opt,name=barcode,proto3,oneof" json:"barcode,omitempty"`
	Name           string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Price          *float64               `protobuf:"fixed64,6,opt,name=price,proto3,oneof" json:"price,omitempty"`
	CostPrice      *float64               `protobuf:"fixed64,7,opt,name=cost_price,json=costPrice,proto3,oneof" json:"cost_price,omitempty"`
	CompareAtPrice *float64               `protobuf:"fixed64,8,opt,name=compare_at_price,json=compareAtPrice,proto3,oneof" json:"compare_at_price,omitempty"`
	StockQuantity  int32                  `protobuf:"varint,9,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	Weight         *float64               `protobuf:"fixed64,10,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Attributes     *structpb.Struct       `protobuf:"bytes,11,opt,name=attributes,proto3" json:"attributes,omitempty"`
	IsActive       bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_product_product_dev_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{6}
}

func (x *Variant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Variant) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Variant) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *Variant) GetBarcode() string {
	if x != nil && x.Barcode != nil {
		return *x.Barcode
	}
	return ""
}

func (x *Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variant) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *Variant) GetCostPrice() float64 {
	if x != nil && x.CostPrice != nil {
		return *x.CostPrice
	}
	return 0
}

func (x *Variant) GetCompareAtPrice() float64 {
	if x != nil && x.CompareAtPrice != nil {
		return *x.CompareAtPrice
	}
	return 0
}

func (x *Variant) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Variant) GetWeight() float64 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *Variant) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Variant) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Variant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Variant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_product_product_dev_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{7}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShopId         string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CategoryId     *string                `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Sku            *string                `protobuf:"bytes,3,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	Barcode        *string                `protobuf:"bytes,4,opt,name=barcode,proto3,oneof" json:"barcode,omitempty"`
	Name           string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Detail         *string                `protobuf:"bytes,7,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	Price          float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	CostPrice      *float64               `protobuf:"fixed64,9,opt,name=cost_price,json=costPrice,proto3,oneof" json:"cost_price,omitempty"`
	CompareAtPrice *float64               `protobuf:"fixed64,10,opt,name=compare_at_price,json=compareAtPrice,proto3,oneof" json:"compare_at_price,omitempty"`
	StockQuantity  int32                  `protobuf:"varint,11,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	MinStockLevel  *int32                 `protobuf:"varint,12,opt,name=min_stock_level,json=minStockLevel,proto3,oneof" json:"min_stock_level,omitempty"`
	MaxStockLevel  *int32                 `protobuf:"varint,13,opt,name=max_stock_level,json=maxStockLevel,proto3,oneof" json:"max_stock_level,omitempty"`
	Unit           *string                `protobuf:"bytes,14,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	Weight         *float64               `protobuf:"fixed64,15,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	WeightUnit     *string                `protobuf:"bytes,16,opt,name=weight_unit,json=weightUnit,proto3,oneof" json:"weight_unit,omitempty"`
	IsActive       bool                   `protobuf:"varint,17,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsTaxable      bool                   `protobuf:"varint,18,opt,name=is_taxable,json=isTaxable,proto3" json:"is_taxable,omitempty"`
	TaxRate        *float64               `protobuf:"fixed64,19,opt,name=tax_rate,json=taxRate,proto3,oneof" json:"tax_rate,omitempty"`
	TrackInventory bool                   `protobuf:"varint,20,opt,name=track_inventory,json=trackInventory,proto3" json:"track_inventory,omitempty"`
	AllowBackorder bool                   `protobuf:"varint,21,opt,name=allow_backorder,json=allowBackorder,proto3" json:"allow_backorder,omitempty"`
	IsFeatured     bool                   `protobuf:"varint,22,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	Media          []*MediaRequest        `protobuf:"bytes,23,rep,name=media,proto3" json:"media,omitempty"`
	TagIds         []string               `protobuf:"bytes,24,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,25,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_product_product_dev_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *CreateRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *CreateRequest) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *CreateRequest) GetBarcode() string {
	if x != nil && x.Barcode != nil {
		return *x.Barcode
	}
	return ""
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateRequest) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

func (x *CreateRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateRequest) GetCostPrice() float64 {
	if x != nil && x.CostPrice != nil {
		return *x.CostPrice
	}
	return 0
}

func (x *CreateRequest) GetCompareAtPrice() float64 {
	if x != nil && x.CompareAtPrice != nil {
		return *x.CompareAtPrice
	}
	return 0
}

func (x *CreateRequest) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *CreateRequest) GetMinStockLevel() int32 {
	if x != nil && x.MinStockLevel != nil {
		return *x.MinStockLevel
	}
	return 0
}

func (x *CreateRequest) GetMaxStockLevel() int32 {
	if x != nil && x.MaxStockLevel != nil {
		return *x.MaxStockLevel
	}
	return 0
}

func (x *CreateRequest) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *CreateRequest) GetWeight() float64 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *CreateRequest) GetWeightUnit() string {
	if x != nil && x.WeightUnit != nil {
		return *x.WeightUnit
	}
	return ""
}

func (x *CreateRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateRequest) GetIsTaxable() bool {
	if x != nil {
		return x.IsTaxable
	}
	return false
}

func (x *CreateRequest) GetTaxRate() float64 {
	if x != nil && x.TaxRate != nil {
		return *x.TaxRate
	}
	return 0
}

func (x *CreateRequest) GetTrackInventory() bool {
	if x != nil {
		return x.TrackInventory
	}
	return false
}

func (x *CreateRequest) GetAllowBackorder() bool {
	if x != nil {
		return x.AllowBackorder
	}
	return false
}

func (x *CreateRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *CreateRequest) GetMedia() []*MediaRequest {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *CreateRequest) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *CreateRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaUrl      string                 `protobuf:"bytes,1,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,3,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	IsThumbnail   bool                   `protobuf:"varint,4,opt,name=is_thumbnail,json=isThumbnail,proto3" json:"is_thumbnail,omitempty"`
	AltText       *string                `protobuf:"bytes,5,opt,name=alt_text,json=altText,proto3,oneof" json:"alt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaRequest) Reset() {
	*x = MediaRequest{}
	mi := &file_product_product_dev_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRequest) ProtoMessage() {}

func (x *MediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRequest.ProtoReflect.Descriptor instead.
func (*MediaRequest) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{9}
}

func (x *MediaRequest) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *MediaRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *MediaRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *MediaRequest) GetIsThumbnail() bool {
	if x != nil {
		return x.IsThumbnail
	}
	return false
}

func (x *MediaRequest) GetAltText() string {
	if x != nil && x.AltText != nil {
		return *x.AltText
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_product_product_dev_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{10}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type GetDetailRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId                string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	IncludeCategory       bool                   `protobuf:"varint,3,opt,name=include_category,json=includeCategory,proto3" json:"include_category,omitempty"`
	IncludeCategoryParent bool                   `protobuf:"varint,4,opt,name=include_category_parent,json=includeCategoryParent,proto3" json:"include_category_parent,omitempty"`
	IncludeMedia          bool                   `protobuf:"varint,5,opt,name=include_media,json=includeMedia,proto3" json:"include_media,omitempty"`
	IncludeVariants       bool                   `protobuf:"varint,6,opt,name=include_variants,json=includeVariants,proto3" json:"include_variants,omitempty"`
	IncludeTags           bool                   `protobuf:"varint,7,opt,name=include_tags,json=includeTags,proto3" json:"include_tags,omitempty"`
	IncludeShop           bool                   `protobuf:"varint,8,opt,name=include_shop,json=includeShop,proto3" json:"include_shop,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetDetailRequest) Reset() {
	*x = GetDetailRequest{}
	mi := &file_product_product_dev_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailRequest) ProtoMessage() {}

func (x *GetDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailRequest.ProtoReflect.Descriptor instead.
func (*GetDetailRequest) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{11}
}

func (x *GetDetailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDetailRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *GetDetailRequest) GetIncludeCategory() bool {
	if x != nil {
		return x.IncludeCategory
	}
	return false
}

func (x *GetDetailRequest) GetIncludeCategoryParent() bool {
	if x != nil {
		return x.IncludeCategoryParent
	}
	return false
}

func (x *GetDetailRequest) GetIncludeMedia() bool {
	if x != nil {
		return x.IncludeMedia
	}
	return false
}

func (x *GetDetailRequest) GetIncludeVariants() bool {
	if x != nil {
		return x.IncludeVariants
	}
	return false
}

func (x *GetDetailRequest) GetIncludeTags() bool {
	if x != nil {
		return x.IncludeTags
	}
	return false
}

func (x *GetDetailRequest) GetIncludeShop() bool {
	if x != nil {
		return x.IncludeShop
	}
	return false
}

type ListRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShopId          string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CategoryId      *string                `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Search          *string                `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	IsActive        *bool                  `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	IsFeatured      *bool                  `protobuf:"varint,5,opt,name=is_featured,json=isFeatured,proto3,oneof" json:"is_featured,omitempty"`
	TagIds          []string               `protobuf:"bytes,6,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	MinPrice        *float64               `protobuf:"fixed64,7,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice        *float64               `protobuf:"fixed64,8,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	LowStockOnly    bool                   `protobuf:"varint,9,opt,name=low_stock_only,json=lowStockOnly,proto3" json:"low_stock_only,omitempty"`
	SortBy          string                 `protobuf:"bytes,10,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder       string                 `protobuf:"bytes,11,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Page            int32                  `protobuf:"varint,12,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int32                  `protobuf:"varint,13,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	IncludeCategory bool                   `protobuf:"varint,14,opt,name=include_category,json=includeCategory,proto3" json:"include_category,omitempty"`
	IncludeMedia    bool                   `protobuf:"varint,15,opt,name=include_media,json=includeMedia,proto3" json:"include_media,omitempty"`
	IncludeTags     bool                   `protobuf:"varint,16,opt,name=include_tags,json=includeTags,proto3" json:"include_tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_product_product_dev_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{12}
}

func (x *ListRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ListRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *ListRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListRequest) GetIsFeatured() bool {
	if x != nil && x.IsFeatured != nil {
		return *x.IsFeatured
	}
	return false
}

func (x *ListRequest) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *ListRequest) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ListRequest) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *ListRequest) GetLowStockOnly() bool {
	if x != nil {
		return x.LowStockOnly
	}
	return false
}

func (x *ListRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetIncludeCategory() bool {
	if x != nil {
		return x.IncludeCategory
	}
	return false
}

func (x *ListRequest) GetIncludeMedia() bool {
	if x != nil {
		return x.IncludeMedia
	}
	return false
}

func (x *ListRequest) GetIncludeTags() bool {
	if x != nil {
		return x.IncludeTags
	}
	return false
}

type UpdateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId         string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CategoryId     *string                `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Sku            *string                `protobuf:"bytes,4,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	Barcode        *string                `protobuf:"bytes,5,opt,name=barcode,proto3,oneof" json:"barcode,omitempty"`
	Name           *string                `protobuf:"bytes,6,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Detail         *string                `protobuf:"bytes,8,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	Price          *float64               `protobuf:"fixed64,9,opt,name=price,proto3,oneof" json:"price,omitempty"`
	CostPrice      *float64               `protobuf:"fixed64,10,opt,name=cost_price,json=costPrice,proto3,oneof" json:"cost_price,omitempty"`
	CompareAtPrice *float64               `protobuf:"fixed64,11,opt,name=compare_at_price,json=compareAtPrice,proto3,oneof" json:"compare_at_price,omitempty"`
	MinStockLevel  *int32                 `protobuf:"varint,12,opt,name=min_stock_level,json=minStockLevel,proto3,oneof" json:"min_stock_level,omitempty"`
	MaxStockLevel  *int32                 `protobuf:"varint,13,opt,name=max_stock_level,json=maxStockLevel,proto3,oneof" json:"max_stock_level,omitempty"`
	IsActive       *bool                  `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	IsFeatured     *bool                  `protobuf:"varint,15,opt,name=is_featured,json=isFeatured,proto3,oneof" json:"is_featured,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,16,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_product_product_dev_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *UpdateRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *UpdateRequest) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *UpdateRequest) GetBarcode() string {
	if x != nil && x.Barcode != nil {
		return *x.Barcode
	}
	return ""
}

func (x *UpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRequest) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

func (x *UpdateRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateRequest) GetCostPrice() float64 {
	if x != nil && x.CostPrice != nil {
		return *x.CostPrice
	}
	return 0
}

func (x *UpdateRequest) GetCompareAtPrice() float64 {
	if x != nil && x.CompareAtPrice != nil {
		return *x.CompareAtPrice
	}
	return 0
}

func (x *UpdateRequest) GetMinStockLevel() int32 {
	if x != nil && x.MinStockLevel != nil {
		return *x.MinStockLevel
	}
	return 0
}

func (x *UpdateRequest) GetMaxStockLevel() int32 {
	if x != nil && x.MaxStockLevel != nil {
		return *x.MaxStockLevel
	}
	return 0
}

func (x *UpdateRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateRequest) GetIsFeatured() bool {
	if x != nil && x.IsFeatured != nil {
		return *x.IsFeatured
	}
	return false
}

func (x *UpdateRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	SoftDelete    bool                   `protobuf:"varint,3,opt,name=soft_delete,json=softDelete,proto3" json:"soft_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_product_product_dev_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *DeleteRequest) GetSoftDelete() bool {
	if x != nil {
		return x.SoftDelete
	}
	return false
}

type StockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId         string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	QuantityChange int32                  `protobuf:"varint,3,opt,name=quantity_change,json=quantityChange,proto3" json:"quantity_change,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StockRequest) Reset() {
	*x = StockRequest{}
	mi := &file_product_product_dev_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRequest) ProtoMessage() {}

func (x *StockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRequest.ProtoReflect.Descriptor instead.
func (*StockRequest) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{15}
}

func (x *StockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *StockRequest) GetQuantityChange() int32 {
	if x != nil {
		return x.QuantityChange
	}
	return 0
}

func (x *StockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BulkStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Updates       []*StockUpdate         `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkStockRequest) Reset() {
	*x = BulkStockRequest{}
	mi := &file_product_product_dev_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkStockRequest) ProtoMessage() {}

func (x *BulkStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkStockRequest.ProtoReflect.Descriptor instead.
func (*BulkStockRequest) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{16}
}

func (x *BulkStockRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *BulkStockRequest) GetUpdates() []*StockUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type StockUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	QuantityChange int32                  `protobuf:"varint,2,opt,name=quantity_change,json=quantityChange,proto3" json:"quantity_change,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StockUpdate) Reset() {
	*x = StockUpdate{}
	mi := &file_product_product_dev_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdate) ProtoMessage() {}

func (x *StockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdate.ProtoReflect.Descriptor instead.
func (*StockUpdate) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{17}
}

func (x *StockUpdate) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockUpdate) GetQuantityChange() int32 {
	if x != nil {
		return x.QuantityChange
	}
	return 0
}

func (x *StockUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductDetail         `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_product_dev_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{18}
}

func (x *ProductResponse) GetProduct() *ProductDetail {
	if x != nil {
		return x.Product
	}
	return nil
}

type DetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductDetail         `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailResponse) Reset() {
	*x = DetailResponse{}
	mi := &file_product_product_dev_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResponse) ProtoMessage() {}

func (x *DetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResponse.ProtoReflect.Descriptor instead.
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{19}
}

func (x *DetailResponse) GetProduct() *ProductDetail {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductDetail       `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_product_product_dev_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{20}
}

func (x *ListResponse) GetProducts() []*ProductDetail {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type BulkStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductDetail       `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Errors        []*StockError          `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorCount    int32                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkStockResponse) Reset() {
	*x = BulkStockResponse{}
	mi := &file_product_product_dev_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkStockResponse) ProtoMessage() {}

func (x *BulkStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkStockResponse.ProtoReflect.Descriptor instead.
func (*BulkStockResponse) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{21}
}

func (x *BulkStockResponse) GetProducts() []*ProductDetail {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *BulkStockResponse) GetErrors() []*StockError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BulkStockResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkStockResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

type StockError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockError) Reset() {
	*x = StockError{}
	mi := &file_product_product_dev_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockError) ProtoMessage() {}

func (x *StockError) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_dev_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockError.ProtoReflect.Descriptor instead.
func (*StockError) Descriptor() ([]byte, []int) {
	return file_product_product_dev_proto_rawDescGZIP(), []int{22}
}

func (x *StockError) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_product_product_dev_proto protoreflect.FileDescriptor

const file_product_product_dev_proto_rawDesc = "" +
	"\n" +
	"\x19product/product.dev.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x97\t\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12$\n" +
	"\vcategory_id\x18\x03 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12\x15\n" +
	"\x03sku\x18\x04 \x01(\tH\x01R\x03sku\x88\x01\x01\x12\x1d\n" +
	"\abarcode\x18\x05 \x01(\tH\x02R\abarcode\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x03R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06detail\x18\b \x01(\tH\x04R\x06detail\x88\x01\x01\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"cost_price\x18\n" +
	" \x01(\x01R\tcostPrice\x12-\n" +
	"\x10compare_at_price\x18\v \x01(\x01H\x05R\x0ecompareAtPrice\x88\x01\x01\x12%\n" +
	"\x0estock_quantity\x18\f \x01(\x05R\rstockQuantity\x12&\n" +
	"\x0fmin_stock_level\x18\r \x01(\x05R\rminStockLevel\x12+\n" +
	"\x0fmax_stock_level\x18\x0e \x01(\x05H\x06R\rmaxStockLevel\x88\x01\x01\x12\x12\n" +
	"\x04unit\x18\x0f \x01(\tR\x04unit\x12\x1b\n" +
	"\x06weight\x18\x10 \x01(\x01H\aR\x06weight\x88\x01\x01\x12\x1f\n" +
	"\vweight_unit\x18\x11 \x01(\tR\n" +
	"weightUnit\x12'\n" +
	"\x0fthumbnail_index\x18\x12 \x01(\x05R\x0ethumbnailIndex\x12\x1b\n" +
	"\tis_active\x18\x13 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_taxable\x18\x14 \x01(\bR\tisTaxable\x12\x19\n" +
	"\btax_rate\x18\x15 \x01(\x01R\ataxRate\x12'\n" +
	"\x0ftrack_inventory\x18\x16 \x01(\bR\x0etrackInventory\x12'\n" +
	"\x0fallow_backorder\x18\x17 \x01(\bR\x0eallowBackorder\x12\x1f\n" +
	"\vis_featured\x18\x18 \x01(\bR\n" +
	"isFeatured\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x19 \x01(\x05R\tsortOrder\x123\n" +
	"\bmetadata\x18\x1a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1c \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x1d \x01(\v2\x1a.google.protobuf.TimestampH\bR\tdeletedAt\x88\x01\x01B\x0e\n" +
	"\f_category_idB\x06\n" +
	"\x04_skuB\n" +
	"\n" +
	"\b_barcodeB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_detailB\x13\n" +
	"\x11_compare_at_priceB\x12\n" +
	"\x10_max_stock_levelB\t\n" +
	"\a_weightB\r\n" +
	"\v_deleted_at\"\x86\x01\n" +
	"\x0eProductSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x03sku\x18\x03 \x01(\tH\x00R\x03sku\x88\x01\x01\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActiveB\x06\n" +
	"\x04_sku\"\xab\x02\n" +
	"\rProductDetail\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\x126\n" +
	"\bcategory\x18\x02 \x01(\v2\x15.product.CategoryInfoH\x00R\bcategory\x88\x01\x01\x12$\n" +
	"\x05media\x18\x03 \x03(\v2\x0e.product.MediaR\x05media\x12,\n" +
	"\bvariants\x18\x04 \x03(\v2\x10.product.VariantR\bvariants\x12 \n" +
	"\x04tags\x18\x05 \x03(\v2\f.product.TagR\x04tags\x12*\n" +
	"\x04shop\x18\x06 \x01(\v2\x11.product.ShopInfoH\x01R\x04shop\x88\x01\x01B\v\n" +
	"\t_categoryB\a\n" +
	"\x05_shop\"\xb5\x01\n" +
	"\fCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\tparent_id\x18\x04 \x01(\tH\x00R\bparentId\x88\x01\x01\x122\n" +
	"\x06parent\x18\x05 \x01(\v2\x15.product.CategoryInfoH\x01R\x06parent\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\t\n" +
	"\a_parent\"[\n" +
	"\bShopInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\blogo_url\x18\x03 \x01(\tH\x00R\alogoUrl\x88\x01\x01B\v\n" +
	"\t_logo_url\"\xa2\x02\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1b\n" +
	"\tmedia_url\x18\x03 \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12#\n" +
	"\rdisplay_order\x18\x05 \x01(\x05R\fdisplayOrder\x12!\n" +
	"\fis_thumbnail\x18\x06 \x01(\bR\visThumbnail\x12\x1e\n" +
	"\balt_text\x18\a \x01(\tH\x00R\aaltText\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\v\n" +
	"\t_alt_text\"\xcd\x04\n" +
	"\aVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x15\n" +
	"\x03sku\x18\x03 \x01(\tH\x00R\x03sku\x88\x01\x01\x12\x1d\n" +
	"\abarcode\x18\x04 \x01(\tH\x01R\abarcode\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x19\n" +
	"\x05price\x18\x06 \x01(\x01H\x02R\x05price\x88\x01\x01\x12\"\n" +
	"\n" +
	"cost_price\x18\a \x01(\x01H\x03R\tcostPrice\x88\x01\x01\x12-\n" +
	"\x10compare_at_price\x18\b \x01(\x01H\x04R\x0ecompareAtPrice\x88\x01\x01\x12%\n" +
	"\x0estock_quantity\x18\t \x01(\x05R\rstockQuantity\x12\x1b\n" +
	"\x06weight\x18\n" +
	" \x01(\x01H\x05R\x06weight\x88\x01\x01\x127\n" +
	"\n" +
	"attributes\x18\v \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x06\n" +
	"\x04_skuB\n" +
	"\n" +
	"\b_barcodeB\b\n" +
	"\x06_priceB\r\n" +
	"\v_cost_priceB\x13\n" +
	"\x11_compare_at_priceB\t\n" +
	"\a_weight\"\x91\x01\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa8\b\n" +
	"\rCreateRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12\x15\n" +
	"\x03sku\x18\x03 \x01(\tH\x01R\x03sku\x88\x01\x01\x12\x1d\n" +
	"\abarcode\x18\x04 \x01(\tH\x02R\abarcode\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x03R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06detail\x18\a \x01(\tH\x04R\x06detail\x88\x01\x01\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\"\n" +
	"\n" +
	"cost_price\x18\t \x01(\x01H\x05R\tcostPrice\x88\x01\x01\x12-\n" +
	"\x10compare_at_price\x18\n" +
	" \x01(\x01H\x06R\x0ecompareAtPrice\x88\x01\x01\x12%\n" +
	"\x0estock_quantity\x18\v \x01(\x05R\rstockQuantity\x12+\n" +
	"\x0fmin_stock_level\x18\f \x01(\x05H\aR\rminStockLevel\x88\x01\x01\x12+\n" +
	"\x0fmax_stock_level\x18\r \x01(\x05H\bR\rmaxStockLevel\x88\x01\x01\x12\x17\n" +
	"\x04unit\x18\x0e \x01(\tH\tR\x04unit\x88\x01\x01\x12\x1b\n" +
	"\x06weight\x18\x0f \x01(\x01H\n" +
	"R\x06weight\x88\x01\x01\x12$\n" +
	"\vweight_unit\x18\x10 \x01(\tH\vR\n" +
	"weightUnit\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\x11 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_taxable\x18\x12 \x01(\bR\tisTaxable\x12\x1e\n" +
	"\btax_rate\x18\x13 \x01(\x01H\fR\ataxRate\x88\x01\x01\x12'\n" +
	"\x0ftrack_inventory\x18\x14 \x01(\bR\x0etrackInventory\x12'\n" +
	"\x0fallow_backorder\x18\x15 \x01(\bR\x0eallowBackorder\x12\x1f\n" +
	"\vis_featured\x18\x16 \x01(\bR\n" +
	"isFeatured\x12+\n" +
	"\x05media\x18\x17 \x03(\v2\x15.product.MediaRequestR\x05media\x12\x17\n" +
	"\atag_ids\x18\x18 \x03(\tR\x06tagIds\x123\n" +
	"\bmetadata\x18\x19 \x01(\v2\x17.google.protobuf.StructR\bmetadataB\x0e\n" +
	"\f_category_idB\x06\n" +
	"\x04_skuB\n" +
	"\n" +
	"\b_barcodeB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_detailB\r\n" +
	"\v_cost_priceB\x13\n" +
	"\x11_compare_at_priceB\x12\n" +
	"\x10_min_stock_levelB\x12\n" +
	"\x10_max_stock_levelB\a\n" +
	"\x05_unitB\t\n" +
	"\a_weightB\x0e\n" +
	"\f_weight_unitB\v\n" +
	"\t_tax_rate\"\xbf\x01\n" +
	"\fMediaRequest\x12\x1b\n" +
	"\tmedia_url\x18\x01 \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12#\n" +
	"\rdisplay_order\x18\x03 \x01(\x05R\fdisplayOrder\x12!\n" +
	"\fis_thumbnail\x18\x04 \x01(\bR\visThumbnail\x12\x1e\n" +
	"\balt_text\x18\x05 \x01(\tH\x00R\aaltText\x88\x01\x01B\v\n" +
	"\t_alt_text\"5\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\"\xb4\x02\n" +
	"\x10GetDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12)\n" +
	"\x10include_category\x18\x03 \x01(\bR\x0fincludeCategory\x126\n" +
	"\x17include_category_parent\x18\x04 \x01(\bR\x15includeCategoryParent\x12#\n" +
	"\rinclude_media\x18\x05 \x01(\bR\fincludeMedia\x12)\n" +
	"\x10include_variants\x18\x06 \x01(\bR\x0fincludeVariants\x12!\n" +
	"\finclude_tags\x18\a \x01(\bR\vincludeTags\x12!\n" +
	"\finclude_shop\x18\b \x01(\bR\vincludeShop\"\xe5\x04\n" +
	"\vListRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x01R\x06search\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x04 \x01(\bH\x02R\bisActive\x88\x01\x01\x12$\n" +
	"\vis_featured\x18\x05 \x01(\bH\x03R\n" +
	"isFeatured\x88\x01\x01\x12\x17\n" +
	"\atag_ids\x18\x06 \x03(\tR\x06tagIds\x12 \n" +
	"\tmin_price\x18\a \x01(\x01H\x04R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\b \x01(\x01H\x05R\bmaxPrice\x88\x01\x01\x12$\n" +
	"\x0elow_stock_only\x18\t \x01(\bR\flowStockOnly\x12\x17\n" +
	"\asort_by\x18\n" +
	" \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\v \x01(\tR\tsortOrder\x12\x12\n" +
	"\x04page\x18\f \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\r \x01(\x05R\bpageSize\x12)\n" +
	"\x10include_category\x18\x0e \x01(\bR\x0fincludeCategory\x12#\n" +
	"\rinclude_media\x18\x0f \x01(\bR\fincludeMedia\x12!\n" +
	"\finclude_tags\x18\x10 \x01(\bR\vincludeTagsB\x0e\n" +
	"\f_category_idB\t\n" +
	"\a_searchB\f\n" +
	"\n" +
	"_is_activeB\x0e\n" +
	"\f_is_featuredB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_price\"\x84\x06\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12$\n" +
	"\vcategory_id\x18\x03 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12\x15\n" +
	"\x03sku\x18\x04 \x01(\tH\x01R\x03sku\x88\x01\x01\x12\x1d\n" +
	"\abarcode\x18\x05 \x01(\tH\x02R\abarcode\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tH\x03R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x04R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06detail\x18\b \x01(\tH\x05R\x06detail\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\t \x01(\x01H\x06R\x05price\x88\x01\x01\x12\"\n" +
	"\n" +
	"cost_price\x18\n" +
	" \x01(\x01H\aR\tcostPrice\x88\x01\x01\x12-\n" +
	"\x10compare_at_price\x18\v \x01(\x01H\bR\x0ecompareAtPrice\x88\x01\x01\x12+\n" +
	"\x0fmin_stock_level\x18\f \x01(\x05H\tR\rminStockLevel\x88\x01\x01\x12+\n" +
	"\x0fmax_stock_level\x18\r \x01(\x05H\n" +
	"R\rmaxStockLevel\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x0e \x01(\bH\vR\bisActive\x88\x01\x01\x12$\n" +
	"\vis_featured\x18\x0f \x01(\bH\fR\n" +
	"isFeatured\x88\x01\x01\x128\n" +
	"\bmetadata\x18\x10 \x01(\v2\x17.google.protobuf.StructH\rR\bmetadata\x88\x01\x01B\x0e\n" +
	"\f_category_idB\x06\n" +
	"\x04_skuB\n" +
	"\n" +
	"\b_barcodeB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_detailB\b\n" +
	"\x06_priceB\r\n" +
	"\v_cost_priceB\x13\n" +
	"\x11_compare_at_priceB\x12\n" +
	"\x10_min_stock_levelB\x12\n" +
	"\x10_max_stock_levelB\f\n" +
	"\n" +
	"_is_activeB\x0e\n" +
	"\f_is_featuredB\v\n" +
	"\t_metadata\"Y\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x1f\n" +
	"\vsoft_delete\x18\x03 \x01(\bR\n" +
	"softDelete\"\x87\x01\n" +
	"\fStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12'\n" +
	"\x0fquantity_change\x18\x03 \x01(\x05R\x0equantityChange\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"[\n" +
	"\x10BulkStockRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12.\n" +
	"\aupdates\x18\x02 \x03(\v2\x14.product.StockUpdateR\aupdates\"m\n" +
	"\vStockUpdate\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12'\n" +
	"\x0fquantity_change\x18\x02 \x01(\x05R\x0equantityChange\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"C\n" +
	"\x0fProductResponse\x120\n" +
	"\aproduct\x18\x01 \x01(\v2\x16.product.ProductDetailR\aproduct\"B\n" +
	"\x0eDetailResponse\x120\n" +
	"\aproduct\x18\x01 \x01(\v2\x16.product.ProductDetailR\aproduct\"\x89\x01\n" +
	"\fListResponse\x122\n" +
	"\bproducts\x18\x01 \x03(\v2\x16.product.ProductDetailR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xba\x01\n" +
	"\x11BulkStockResponse\x122\n" +
	"\bproducts\x18\x01 \x03(\v2\x16.product.ProductDetailR\bproducts\x12+\n" +
	"\x06errors\x18\x02 \x03(\v2\x13.product.StockErrorR\x06errors\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x05R\n" +
	"errorCount\"P\n" +
	"\n" +
	"StockError\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xf8\x03\n" +
	"\x0eProductService\x12:\n" +
	"\x06Create\x12\x16.product.CreateRequest\x1a\x18.product.ProductResponse\x124\n" +
	"\x03Get\x12\x13.product.GetRequest\x1a\x18.product.ProductResponse\x12?\n" +
	"\tGetDetail\x12\x19.product.GetDetailRequest\x1a\x17.product.DetailResponse\x123\n" +
	"\x04List\x12\x14.product.ListRequest\x1a\x15.product.ListResponse\x12:\n" +
	"\x06Update\x12\x16.product.UpdateRequest\x1a\x18.product.ProductResponse\x128\n" +
	"\x06Delete\x12\x16.product.DeleteRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\vUpdateStock\x12\x15.product.StockRequest\x1a\x18.product.ProductResponse\x12H\n" +
	"\x0fBulkUpdateStock\x12\x19.product.BulkStockRequest\x1a\x1a.product.BulkStockResponseB\x1eZ\x1cproto/v1/productpb;productpbb\x06proto3"

var (
	file_product_product_dev_proto_rawDescOnce sync.Once
	file_product_product_dev_proto_rawDescData []byte
)

func file_product_product_dev_proto_rawDescGZIP() []byte {
	file_product_product_dev_proto_rawDescOnce.Do(func() {
		file_product_product_dev_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_product_dev_proto_rawDesc), len(file_product_product_dev_proto_rawDesc)))
	})
	return file_product_product_dev_proto_rawDescData
}

var file_product_product_dev_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_product_product_dev_proto_goTypes = []any{
	(*Product)(nil),               // 0: product.Product
	(*ProductSummary)(nil),        // 1: product.ProductSummary
	(*ProductDetail)(nil),         // 2: product.ProductDetail
	(*CategoryInfo)(nil),          // 3: product.CategoryInfo
	(*ShopInfo)(nil),              // 4: product.ShopInfo
	(*Media)(nil),                 // 5: product.Media
	(*Variant)(nil),               // 6: product.Variant
	(*Tag)(nil),                   // 7: product.Tag
	(*CreateRequest)(nil),         // 8: product.CreateRequest
	(*MediaRequest)(nil),          // 9: product.MediaRequest
	(*GetRequest)(nil),            // 10: product.GetRequest
	(*GetDetailRequest)(nil),      // 11: product.GetDetailRequest
	(*ListRequest)(nil),           // 12: product.ListRequest
	(*UpdateRequest)(nil),         // 13: product.UpdateRequest
	(*DeleteRequest)(nil),         // 14: product.DeleteRequest
	(*StockRequest)(nil),          // 15: product.StockRequest
	(*BulkStockRequest)(nil),      // 16: product.BulkStockRequest
	(*StockUpdate)(nil),           // 17: product.StockUpdate
	(*ProductResponse)(nil),       // 18: product.ProductResponse
	(*DetailResponse)(nil),        // 19: product.DetailResponse
	(*ListResponse)(nil),          // 20: product.ListResponse
	(*BulkStockResponse)(nil),     // 21: product.BulkStockResponse
	(*StockError)(nil),            // 22: product.StockError
	(*structpb.Struct)(nil),       // 23: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 25: google.protobuf.Empty
}
var file_product_product_dev_proto_depIdxs = []int32{
	23, // 0: product.Product.metadata:type_name -> google.protobuf.Struct
	24, // 1: product.Product.created_at:type_name -> google.protobuf.Timestamp
	24, // 2: product.Product.updated_at:type_name -> google.protobuf.Timestamp
	24, // 3: product.Product.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 4: product.ProductDetail.product:type_name -> product.Product
	3,  // 5: product.ProductDetail.category:type_name -> product.CategoryInfo
	5,  // 6: product.ProductDetail.media:type_name -> product.Media
	6,  // 7: product.ProductDetail.variants:type_name -> product.Variant
	7,  // 8: product.ProductDetail.tags:type_name -> product.Tag
	4,  // 9: product.ProductDetail.shop:type_name -> product.ShopInfo
	3,  // 10: product.CategoryInfo.parent:type_name -> product.CategoryInfo
	24, // 11: product.Media.created_at:type_name -> google.protobuf.Timestamp
	23, // 12: product.Variant.attributes:type_name -> google.protobuf.Struct
	24, // 13: product.Variant.created_at:type_name -> google.protobuf.Timestamp
	24, // 14: product.Variant.updated_at:type_name -> google.protobuf.Timestamp
	24, // 15: product.Tag.created_at:type_name -> google.protobuf.Timestamp
	9,  // 16: product.CreateRequest.media:type_name -> product.MediaRequest
	23, // 17: product.CreateRequest.metadata:type_name -> google.protobuf.Struct
	23, // 18: product.UpdateRequest.metadata:type_name -> google.protobuf.Struct
	17, // 19: product.BulkStockRequest.updates:type_name -> product.StockUpdate
	2,  // 20: product.ProductResponse.product:type_name -> product.ProductDetail
	2,  // 21: product.DetailResponse.product:type_name -> product.ProductDetail
	2,  // 22: product.ListResponse.products:type_name -> product.ProductDetail
	2,  // 23: product.BulkStockResponse.products:type_name -> product.ProductDetail
	22, // 24: product.BulkStockResponse.errors:type_name -> product.StockError
	8,  // 25: product.ProductService.Create:input_type -> product.CreateRequest
	10, // 26: product.ProductService.Get:input_type -> product.GetRequest
	11, // 27: product.ProductService.GetDetail:input_type -> product.GetDetailRequest
	12, // 28: product.ProductService.List:input_type -> product.ListRequest
	13, // 29: product.ProductService.Update:input_type -> product.UpdateRequest
	14, // 30: product.ProductService.Delete:input_type -> product.DeleteRequest
	15, // 31: product.ProductService.UpdateStock:input_type -> product.StockRequest
	16, // 32: product.ProductService.BulkUpdateStock:input_type -> product.BulkStockRequest
	18, // 33: product.ProductService.Create:output_type -> product.ProductResponse
	18, // 34: product.ProductService.Get:output_type -> product.ProductResponse
	19, // 35: product.ProductService.GetDetail:output_type -> product.DetailResponse
	20, // 36: product.ProductService.List:output_type -> product.ListResponse
	18, // 37: product.ProductService.Update:output_type -> product.ProductResponse
	25, // 38: product.ProductService.Delete:output_type -> google.protobuf.Empty
	18, // 39: product.ProductService.UpdateStock:output_type -> product.ProductResponse
	21, // 40: product.ProductService.BulkUpdateStock:output_type -> product.BulkStockResponse
	33, // [33:41] is the sub-list for method output_type
	25, // [25:33] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_product_product_dev_proto_init() }
func file_product_product_dev_proto_init() {
	if File_product_product_dev_proto != nil {
		return
	}
	file_product_product_dev_proto_msgTypes[0].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[1].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[2].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[3].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[4].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[5].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[6].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[8].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[9].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[12].OneofWrappers = []any{}
	file_product_product_dev_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_product_dev_proto_rawDesc), len(file_product_product_dev_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_product_dev_proto_goTypes,
		DependencyIndexes: file_product_product_dev_proto_depIdxs,
		MessageInfos:      file_product_product_dev_proto_msgTypes,
	}.Build()
	File_product_product_dev_proto = out.File
	file_product_product_dev_proto_goTypes = nil
	file_product_product_dev_proto_depIdxs = nil
}
